// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDEBuildingData : IGDEData
    {
        static string spawnCountKey = "spawnCount";
		int _spawnCount;
        public int spawnCount
        {
            get { return _spawnCount; }
            set {
                if (_spawnCount != value)
                {
                    _spawnCount = value;
					GDEDataManager.SetInt(_key, spawnCountKey, _spawnCount);
                }
            }
        }

        static string weightKey = "weight";
		float _weight;
        public float weight
        {
            get { return _weight; }
            set {
                if (_weight != value)
                {
                    _weight = value;
					GDEDataManager.SetFloat(_key, weightKey, _weight);
                }
            }
        }

        static string typeNameKey = "typeName";
		string _typeName;
        public string typeName
        {
            get { return _typeName; }
            set {
                if (_typeName != value)
                {
                    _typeName = value;
					GDEDataManager.SetString(_key, typeNameKey, _typeName);
                }
            }
        }

        static string nickNameKey = "nickName";
		string _nickName;
        public string nickName
        {
            get { return _nickName; }
            set {
                if (_nickName != value)
                {
                    _nickName = value;
					GDEDataManager.SetString(_key, nickNameKey, _nickName);
                }
            }
        }

        static string spawnLevelKey = "spawnLevel";
		string _spawnLevel;
        public string spawnLevel
        {
            get { return _spawnLevel; }
            set {
                if (_spawnLevel != value)
                {
                    _spawnLevel = value;
					GDEDataManager.SetString(_key, spawnLevelKey, _spawnLevel);
                }
            }
        }

        static string shapePathKey = "shapePath";
		string _shapePath;
        public string shapePath
        {
            get { return _shapePath; }
            set {
                if (_shapePath != value)
                {
                    _shapePath = value;
					GDEDataManager.SetString(_key, shapePathKey, _shapePath);
                }
            }
        }

        public GDEBuildingData(string key) : base(key)
        {
            GDEDataManager.RegisterItem(this.SchemaName(), key);
        }
        public override Dictionary<string, object> SaveToDict()
		{
			var dict = new Dictionary<string, object>();
			dict.Add(GDMConstants.SchemaKey, "Building");
			
            dict.Merge(true, spawnCount.ToGDEDict(spawnCountKey));
            dict.Merge(true, weight.ToGDEDict(weightKey));
            dict.Merge(true, typeName.ToGDEDict(typeNameKey));
            dict.Merge(true, nickName.ToGDEDict(nickNameKey));
            dict.Merge(true, spawnLevel.ToGDEDict(spawnLevelKey));
            dict.Merge(true, shapePath.ToGDEDict(shapePathKey));
            return dict;
		}

        public override void UpdateCustomItems(bool rebuildKeyList)
        {
        }

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetInt(spawnCountKey, out _spawnCount);
                dict.TryGetFloat(weightKey, out _weight);
                dict.TryGetString(typeNameKey, out _typeName);
                dict.TryGetString(nickNameKey, out _nickName);
                dict.TryGetString(spawnLevelKey, out _spawnLevel);
                dict.TryGetString(shapePathKey, out _shapePath);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _spawnCount = GDEDataManager.GetInt(_key, spawnCountKey, _spawnCount);
            _weight = GDEDataManager.GetFloat(_key, weightKey, _weight);
            _typeName = GDEDataManager.GetString(_key, typeNameKey, _typeName);
            _nickName = GDEDataManager.GetString(_key, nickNameKey, _nickName);
            _spawnLevel = GDEDataManager.GetString(_key, spawnLevelKey, _spawnLevel);
            _shapePath = GDEDataManager.GetString(_key, shapePathKey, _shapePath);
        }

        public GDEBuildingData ShallowClone()
		{
			string newKey = Guid.NewGuid().ToString();
			GDEBuildingData newClone = new GDEBuildingData(newKey);

            newClone.spawnCount = spawnCount;
            newClone.weight = weight;
            newClone.typeName = typeName;
            newClone.nickName = nickName;
            newClone.spawnLevel = spawnLevel;
            newClone.shapePath = shapePath;

            return newClone;
		}

        public GDEBuildingData DeepClone()
		{
			GDEBuildingData newClone = ShallowClone();
            return newClone;
		}

        public void Reset_spawnCount()
        {
            GDEDataManager.ResetToDefault(_key, spawnCountKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(spawnCountKey, out _spawnCount);
        }

        public void Reset_weight()
        {
            GDEDataManager.ResetToDefault(_key, weightKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetFloat(weightKey, out _weight);
        }

        public void Reset_typeName()
        {
            GDEDataManager.ResetToDefault(_key, typeNameKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(typeNameKey, out _typeName);
        }

        public void Reset_nickName()
        {
            GDEDataManager.ResetToDefault(_key, nickNameKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(nickNameKey, out _nickName);
        }

        public void Reset_spawnLevel()
        {
            GDEDataManager.ResetToDefault(_key, spawnLevelKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(spawnLevelKey, out _spawnLevel);
        }

        public void Reset_shapePath()
        {
            GDEDataManager.ResetToDefault(_key, shapePathKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(shapePathKey, out _shapePath);
        }

        public void ResetAll()
        {
            GDEDataManager.ResetToDefault(_key, typeNameKey);
            GDEDataManager.ResetToDefault(_key, nickNameKey);
            GDEDataManager.ResetToDefault(_key, weightKey);
            GDEDataManager.ResetToDefault(_key, spawnLevelKey);
            GDEDataManager.ResetToDefault(_key, spawnCountKey);
            GDEDataManager.ResetToDefault(_key, shapePathKey);


            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
