// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public partial class GDESchemaKeys
    {
        public static string Taco = "Taco";
        public static string Deco = "Deco";
        public static string Weapon = "Weapon";
        public static string Projectile = "Projectile";
        public static string Npc = "Npc";
        public static string Building = "Building";
    }
}
